#!/bin/sh
# Kiro Adapter Generator for Aegis
# Outputs .kiro/rules.md format for Kiro agent.

set -eu

BASE_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

echo "<!-- Generated by Aegis AI Framework for Kiro -->"
echo ""
"$BASE_DIR/runtime/generators/generator.sh" "$*"
