#!/bin/sh
# Qwen Adapter Generator for Aegis
# Outputs QWEN.md format for Qwen Code.

set -eu

BASE_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

echo "<!-- Generated by Aegis AI Framework for Qwen Code -->"
echo ""
"$BASE_DIR/runtime/generators/generator.sh" "$*"
