#!/bin/sh
# Claude Adapter Generator for Aegis
# Outputs CLAUDE.md format for Claude Code / Claude Desktop.

set -eu

BASE_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

echo "<!-- Generated by Aegis AI Framework for Claude Code / Claude Desktop -->"
echo ""
"$BASE_DIR/runtime/generators/generator.sh" "$*"
