#!/bin/sh
# Gemini Adapter Generator for Aegis
# Outputs AGENTS.md format for Gemini CLI / Gemini App.

set -eu

BASE_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

echo "<!-- Generated by Aegis AI Framework for Gemini CLI / Gemini App -->"
echo ""
"$BASE_DIR/runtime/generators/generator.sh" "$*"
