#!/bin/sh
# Codex Adapter Generator for Aegis
# Outputs codex.md format for OpenAI Codex / ChatGPT.

set -eu

BASE_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

echo "<!-- Generated by Aegis AI Framework for OpenAI Codex / ChatGPT -->"
echo ""
"$BASE_DIR/runtime/generators/generator.sh" "$*"
