"""
Aegis AI Operating System — Distributed Multi-Agent Coordination & Event Bus Demo
Demonstrates:
1. Multi-agent registration & capability discovery
2. High-performance secure event bus (Publish/Subscribe & Request/Reply)
3. Deterministic task coordinator routing & capability matching
4. Circular delegation & recursion protection
5. Secret redaction barrier on multi-agent event payloads
6. Performance benchmarking & latency telemetry
"""

import os
import sys
import time
import tempfile
from typing import Dict, Any

# Ensure parent directory is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from runtime.src.config import AegisConfig
from runtime.src.plugin import PluginPermission
from runtime.src.event_bus import SecureEventBus, AgentEvent, EventPriority
from runtime.src.agents import (
    AgentRegistry, TaskCoordinator, AgentInterface, AgentDescriptor,
    AgentCapabilityToken, AgentTrustLevel, CircularDelegationError
)


class CodeGeneratorAgent(AgentInterface):
    """Core agent responsible for Python code generation."""
    def __init__(self):
        self._descriptor = AgentDescriptor(
            agent_id="agent.core.code_generator",
            name="Aegis Core Code Generator Agent",
            version="1.0.0",
            capabilities=["PYTHON_GEN", "REFACTORING"],
            permissions=[PluginPermission.FILESYSTEM_READ, PluginPermission.FILESYSTEM_WRITE],
            trust_level=AgentTrustLevel.CORE,
            supported_task_types=["generate_code", "refactor_code"]
        )

    def get_descriptor(self) -> AgentDescriptor:
        return self._descriptor

    def initialize(self, ctx: Dict[str, Any]) -> bool:
        return True

    def execute_task(
        self,
        task_id: str,
        task_type: str,
        payload: Dict[str, Any],
        token: AgentCapabilityToken
    ) -> Dict[str, Any]:
        prompt = payload.get("prompt", "def hello(): pass")
        return {
            "status": "COMPLETED",
            "generated_code": f"# Generated by {self._descriptor.agent_id}\n{prompt}\nprint('Hello Aegis Multi-Agent OS!')",
            "token_valid": token.has_permission(PluginPermission.FILESYSTEM_READ)
        }

    def shutdown(self) -> bool:
        return True


class SecurityAuditorAgent(AgentInterface):
    """Trusted agent responsible for scanning security vulnerabilities."""
    def __init__(self):
        self._descriptor = AgentDescriptor(
            agent_id="agent.trusted.security_auditor",
            name="Aegis Security Auditor Agent",
            version="1.0.0",
            capabilities=["SECURITY_SCAN", "VAULT_CHECK"],
            permissions=[PluginPermission.FILESYSTEM_READ],
            trust_level=AgentTrustLevel.TRUSTED,
            supported_task_types=["security_scan"]
        )

    def get_descriptor(self) -> AgentDescriptor:
        return self._descriptor

    def initialize(self, ctx: Dict[str, Any]) -> bool:
        return True

    def execute_task(
        self,
        task_id: str,
        task_type: str,
        payload: Dict[str, Any],
        token: AgentCapabilityToken
    ) -> Dict[str, Any]:
        target_code = payload.get("code", "")
        has_vulnerabilities = "eval(" in target_code or "exec(" in target_code
        return {
            "status": "COMPLETED",
            "vulnerabilities_found": 1 if has_vulnerabilities else 0,
            "security_score": 100 if not has_vulnerabilities else 40
        }

    def shutdown(self) -> bool:
        return True


def run_agents_demo():
    print("================================================================================")
    print("🛡️ AEGIS AI OS — DISTRIBUTED MULTI-AGENT COORDINATION & EVENT BUS DEMO")
    print("================================================================ algorithm\n")

    # Step 1: Initialize Multi-Agent Subsystem
    print("--- 1. INITIALIZING AGENT REGISTRY & SECURE EVENT BUS ---")
    registry = AgentRegistry()
    event_bus = SecureEventBus()
    coordinator = TaskCoordinator(registry, event_bus, max_delegation_depth=3)

    code_agent = CodeGeneratorAgent()
    sec_agent = SecurityAuditorAgent()

    registry.register_agent(code_agent.get_descriptor(), code_agent)
    registry.register_agent(sec_agent.get_descriptor(), sec_agent)

    print(f"✅ Registered {len(registry.list_agents())} Agents:")
    for desc in registry.list_agents():
        print(f"  • [{desc.trust_level.value}] {desc.agent_id} (v{desc.version}) — Tasks: {', '.join(desc.supported_task_types)}")

    # Step 2: Event Bus Publish & Subscribe
    print("\n--- 2. EVENT BUS PUBLISH & SUBSCRIBE DEMO ---")
    received_events = []

    def telemetry_subscriber(evt: AgentEvent):
        received_events.append(evt)
        print(f"  📡 Telemetry Subscriber Received: '{evt.event_type}' from '{evt.source_agent_id}'")

    event_bus.subscribe("auditor_service", "AGENT_HEALTH_CHECK", telemetry_subscriber)

    health_evt = AgentEvent(
        event_type="AGENT_HEALTH_CHECK",
        source_agent_id="agent.core.code_generator",
        payload={"cpu_usage": "1.2%", "status": "OPTIMAL"}
    )
    event_bus.publish(health_evt)
    print("✅ Event published & delivered via SecureEventBus.")

    # Step 3: Request / Reply Event Pattern
    print("\n--- 3. SYNCHRONOUS REQUEST / REPLY PATTERN DEMO ---")
    def echo_responder(evt: AgentEvent):
        return AgentEvent(
            event_type="AGENT_RESPONSE",
            source_agent_id=evt.target_agent_id,
            target_agent_id=evt.source_agent_id,
            correlation_id=evt.correlation_id,
            payload={"reply_msg": f"Acknowledged request '{evt.payload.get('msg')}'"}
        )

    event_bus.subscribe("agent.trusted.security_auditor", "AGENT_QUERY", echo_responder)

    query_evt = AgentEvent(
        event_type="AGENT_QUERY",
        source_agent_id="agent.core.code_generator",
        target_agent_id="agent.trusted.security_auditor",
        payload={"msg": "Requesting audit status update"}
    )
    t0 = time.time()
    reply = event_bus.request_reply(query_evt, timeout_seconds=2.0)
    rt_latency_ms = (time.time() - t0) * 1000.0

    print(f"📥 Request-Reply Received: {reply.payload['reply_msg']}")
    print(f"⏱️ Round-Trip Request/Reply Latency: {rt_latency_ms:.2f} ms")

    # Step 4: Deterministic Task Coordinator Routing
    print("\n--- 4. DETERMINISTIC TASK COORDINATOR ROUTING ---")
    task_res1 = coordinator.submit_task("generate_code", {"prompt": "def calculate_hash(data): return 42"})
    print(f"✅ Code Generation Task Routed to: '{task_res1.assigned_agent_id}'")
    print(f"  • Execution Result: {task_res1.result['status']}")
    print(f"  • Code Output Snippet: {task_res1.result['generated_code'].splitlines()[0]}")
    print(f"  • Execution Time: {task_res1.execution_time_ms:.2f} ms")

    task_res2 = coordinator.submit_task("security_scan", {"code": task_res1.result['generated_code']})
    print(f"✅ Security Audit Task Routed to: '{task_res2.assigned_agent_id}'")
    print(f"  • Security Score: {task_res2.result['security_score']}/100")
    print(f"  • Execution Time: {task_res2.execution_time_ms:.2f} ms")

    # Step 5: Circular Delegation Barrier Enforcement
    print("\n--- 5. CIRCULAR DELEGATION & RECURSION PROTECTION DEMO ---")
    try:
        coordinator.submit_task(
            "generate_code",
            {"prompt": "recursive"},
            delegation_stack=["agent.core.code_generator", "agent.trusted.security_auditor", "agent.core.code_generator"]
        )
    except CircularDelegationError as err:
        print(f"🛡️ Security Barrier PASS: Circular Delegation Blocked: {err}")

    # Step 6: Secret Redaction Barrier on Event Payload
    print("\n--- 6. SECRET REDACTION BARRIER ON MULTI-AGENT PAYLOADS ---")
    secret_evt = AgentEvent(
        event_type="AGENT_HEALTH_CHECK",
        source_agent_id="agent.core.code_generator",
        payload={
            "gemini_api_key": "AIzaSyA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6",
            "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIi"
        }
    )
    event_bus.publish(secret_evt)
    print(f"🔒 Redacted Event Payload: {secret_evt.payload}")

    # Step 7: Performance Benchmark Summary
    print("\n================================================================================")
    print("📊 MULTI-AGENT COORDINATION PERFORMANCE BENCHMARK OVERHEAD SUMMARY")
    print("================================================================================")
    print(f"  - Event Bus Request/Reply Latency : {rt_latency_ms:.2f} ms")
    print(f"  - Task Selection & Routing Latency : {task_res1.execution_time_ms:.2f} ms")
    print("================================================================================")
    print("✅ MULTI-AGENT COORDINATION & EVENT BUS DEMO COMPLETED SUCCESSFULLY!")
    print("================================================================================\n")


if __name__ == "__main__":
    run_agents_demo()
